// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC81SYluOyoaGvlmeBNCyGgefEkMlQMAI',
    appId: '1:372070952768:web:376984000ec20d74b314a5',
    messagingSenderId: '372070952768',
    projectId: 'unify-37894',
    authDomain: 'unify-37894.firebaseapp.com',
    storageBucket: 'unify-37894.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOUlw0obIHyiuulGss3hW5aEALw7BR8Xg',
    appId: '1:372070952768:android:0f8e706f019c1e93b314a5',
    messagingSenderId: '372070952768',
    projectId: 'unify-37894',
    storageBucket: 'unify-37894.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNTEKGscfwckh4hoASRoGx4k6JNfQEE0g',
    appId: '1:372070952768:ios:69dc48404e5d4f30b314a5',
    messagingSenderId: '372070952768',
    projectId: 'unify-37894',
    storageBucket: 'unify-37894.appspot.com',
    iosClientId: '372070952768-j7qn7qamm9fk4qqti8rcnmc6uhoh79qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.unify',
  );
}
